# 声明基础镜像来源
FROM ubuntu:22.04
# 声明工作路径
WORKDIR /im
RUN mkdir -p /im/logs &&\
    mkdir -p /im/data &&\
    mkdir -p /im/conf &&\
    mkdir -p /im/bin
# 将可执行程序文件，拷贝进入镜像
COPY ./build/message_server /im/bin/
# 将可执行程序依赖，拷贝进入镜像
COPY ./depends/ /lib/x86_64-linux-gnu/

COPY ./nc /bin/
# 设置容器的启动默认操作 --- 运行程序
CMD /im/bin/message_server -flagfile=/im/conf/message_server.conf