// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef MESSAGE_ODB_HXX
#define MESSAGE_ODB_HXX

// Begin prologue.
//
#include <odb/boost/version.hxx>
#if ODB_BOOST_VERSION != 2047700 // 2.5.0-b.27
#  error ODB and C++ compilers see different libodb-boost interface versions
#endif
#include <odb/boost/date-time/mysql/gregorian-traits.hxx>
#include <odb/boost/date-time/mysql/posix-time-traits.hxx>
//
// End prologue.

#include <odb/version.hxx>

#if ODB_VERSION != 20477UL
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "message.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // Message
  //
  template <>
  struct class_traits< ::chat_im::Message >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::chat_im::Message >
  {
    public:
    typedef ::chat_im::Message object_type;
    typedef ::chat_im::Message* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // Message
  //
  template <typename A>
  struct query_columns< ::chat_im::Message, id_mysql, A >
  {
    // id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    id_type_;

    static const id_type_ id;

    // message_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    message_id_type_;

    static const message_id_type_ message_id;

    // session_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    session_id_type_;

    static const session_id_type_ session_id;

    // user_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    user_id_type_;

    static const user_id_type_ user_id;

    // message_type
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        unsigned char,
        mysql::id_utiny >::query_type,
      mysql::id_utiny >
    message_type_type_;

    static const message_type_type_ message_type;

    // create_time
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::boost::posix_time::ptime,
        mysql::id_timestamp >::query_type,
      mysql::id_timestamp >
    create_time_type_;

    static const create_time_type_ create_time;

    // content
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::basic_string< char >,
        mysql::id_string >::query_type,
      mysql::id_string >
    content_type_;

    static const content_type_ content;

    // file_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::basic_string< char >,
        mysql::id_string >::query_type,
      mysql::id_string >
    file_id_type_;

    static const file_id_type_ file_id;

    // file_name
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::basic_string< char >,
        mysql::id_string >::query_type,
      mysql::id_string >
    file_name_type_;

    static const file_name_type_ file_name;

    // file_size
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        unsigned int,
        mysql::id_ulong >::query_type,
      mysql::id_ulong >
    file_size_type_;

    static const file_size_type_ file_size;
  };

  template <typename A>
  const typename query_columns< ::chat_im::Message, id_mysql, A >::id_type_
  query_columns< ::chat_im::Message, id_mysql, A >::
  id (A::table_name, "`id`", 0);

  template <typename A>
  const typename query_columns< ::chat_im::Message, id_mysql, A >::message_id_type_
  query_columns< ::chat_im::Message, id_mysql, A >::
  message_id (A::table_name, "`message_id`", 0);

  template <typename A>
  const typename query_columns< ::chat_im::Message, id_mysql, A >::session_id_type_
  query_columns< ::chat_im::Message, id_mysql, A >::
  session_id (A::table_name, "`session_id`", 0);

  template <typename A>
  const typename query_columns< ::chat_im::Message, id_mysql, A >::user_id_type_
  query_columns< ::chat_im::Message, id_mysql, A >::
  user_id (A::table_name, "`user_id`", 0);

  template <typename A>
  const typename query_columns< ::chat_im::Message, id_mysql, A >::message_type_type_
  query_columns< ::chat_im::Message, id_mysql, A >::
  message_type (A::table_name, "`message_type`", 0);

  template <typename A>
  const typename query_columns< ::chat_im::Message, id_mysql, A >::create_time_type_
  query_columns< ::chat_im::Message, id_mysql, A >::
  create_time (A::table_name, "`create_time`", 0);

  template <typename A>
  const typename query_columns< ::chat_im::Message, id_mysql, A >::content_type_
  query_columns< ::chat_im::Message, id_mysql, A >::
  content (A::table_name, "`content`", 0);

  template <typename A>
  const typename query_columns< ::chat_im::Message, id_mysql, A >::file_id_type_
  query_columns< ::chat_im::Message, id_mysql, A >::
  file_id (A::table_name, "`file_id`", 0);

  template <typename A>
  const typename query_columns< ::chat_im::Message, id_mysql, A >::file_name_type_
  query_columns< ::chat_im::Message, id_mysql, A >::
  file_name (A::table_name, "`file_name`", 0);

  template <typename A>
  const typename query_columns< ::chat_im::Message, id_mysql, A >::file_size_type_
  query_columns< ::chat_im::Message, id_mysql, A >::
  file_size (A::table_name, "`file_size`", 0);

  template <typename A>
  struct pointer_query_columns< ::chat_im::Message, id_mysql, A >:
    query_columns< ::chat_im::Message, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::chat_im::Message, id_mysql >:
    public access::object_traits< ::chat_im::Message >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // _id
      //
      unsigned long long _id_value;
      my_bool _id_null;

      // _message_id
      //
      details::buffer _message_id_value;
      unsigned long _message_id_size;
      my_bool _message_id_null;

      // _session_id
      //
      details::buffer _session_id_value;
      unsigned long _session_id_size;
      my_bool _session_id_null;

      // _user_id
      //
      details::buffer _user_id_value;
      unsigned long _user_id_size;
      my_bool _user_id_null;

      // _message_type
      //
      unsigned char _message_type_value;
      my_bool _message_type_null;

      // _create_time
      //
      MYSQL_TIME _create_time_value;
      my_bool _create_time_null;

      // _content
      //
      details::buffer _content_value;
      unsigned long _content_size;
      my_bool _content_null;

      // _file_id
      //
      details::buffer _file_id_value;
      unsigned long _file_id_size;
      my_bool _file_id_null;

      // _file_name
      //
      details::buffer _file_name_value;
      unsigned long _file_name_size;
      my_bool _file_name_null;

      // _file_size
      //
      unsigned int _file_size_value;
      my_bool _file_size_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 10UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::chat_im::Message, id_common >:
    public access::object_traits_impl< ::chat_im::Message, id_mysql >
  {
  };

  // Message
  //
}

#include "message-odb.ixx"

#include <odb/post.hxx>

#endif // MESSAGE_ODB_HXX
