/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */
use chat_im;

DROP TABLE IF EXISTS `message`;

CREATE TABLE `message`
(
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `message_id` varchar
(64) NOT NULL,
  `session_id` varchar
(64) NOT NULL,
  `user_id` varchar
(64) NOT NULL,
  `message_type` TINYINT UNSIGNED NOT NULL,
  `create_time` TIMESTAMP NULL,
  `content` TEXT NULL,
  `file_id` varchar
(64) NULL,
  `file_name` varchar
(128) NULL,
  `file_size` INT UNSIGNED NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `message_id_i`
  ON `message`
(`message_id`);

CREATE INDEX `session_id_i`
  ON `message`
(`session_id`);

INSERT INTO `message`
VALUES
  (null, '消息ID1', '会话ID1', '用户ID1', 0, DATE_SUB(NOW(), INTERVAL 10 SECOND), '消息内容1', null, null, null),
  (null, '消息ID2', '会话ID2', '用户ID2', 0, DATE_SUB(NOW(), INTERVAL 8 SECOND), '消息内容2', null, null, null),
  (null, '消息ID3', '会话ID3', '用户ID3', 0, DATE_SUB(NOW(), INTERVAL 6 SECOND), '消息内容3', null, null, null),
  (null, '消息ID4', '会话ID4', '用户ID4', 0, DATE_SUB(NOW(), INTERVAL 4 SECOND), '消息内容4', null, null, null),
  (null, '消息ID5', '会话ID5', '用户ID5', 0, DATE_SUB(NOW(), INTERVAL 2 SECOND), '消息内容5', null, null, null);
